# Generated by Django 6.0.4 on 2026-04-19 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cargo', models.CharField(max_length=150)),
                ('sistema_turno', models.CharField(choices=[('14x14', '14x14'), ('10x10', '10x10'), ('7x7', '7x7'), ('5x2', '5x2'), ('sin_turno', 'Lunes a Viernes')], max_length=20)),
                ('incluye_alojamiento', models.BooleanField(default=False)),
                ('es_zona_rural', models.BooleanField(default=False)),
                ('estado_activa', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
