# Generated by Django 6.0.4 on 2026-05-31 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_postulacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertalaboral',
            old_name='estado_activa',
            new_name='activa',
        ),
        migrations.RemoveField(
            model_name='ofertalaboral',
            name='es_zona_rural',
        ),
        migrations.RemoveField(
            model_name='ofertalaboral',
            name='sistema_turno',
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='descripcion',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción del trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='es_rural',
            field=models.BooleanField(default=False, verbose_name='Sector Rural'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='sistema_turnos',
            field=models.CharField(choices=[('Lunes a Viernes', 'Jornada Normal (L a V)'), ('14x14', 'Turno 14x14'), ('7x7', 'Turno 7x7'), ('20x10', 'Turno 20x10'), ('Otro', 'Otro sistema de turnos')], default='Lunes a Viernes', max_length=50),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='sueldo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sueldo líquido'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_publicadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='incluye_alojamiento',
            field=models.BooleanField(default=False, verbose_name='Incluye Alojamiento/Campamento'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='titulo_cargo',
            field=models.CharField(max_length=200, verbose_name='Título del Cargo'),
        ),
    ]
