# Generated by Django 6.0.4 on 2026-06-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_estado_activa_ofertalaboral_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='cv_archivo',
            field=models.FileField(blank=True, null=True, upload_to='cvs_candidatos/', verbose_name='Currículum (PDF/Word)'),
        ),
    ]
